### ISSUE TITLE
The "motion" object is not provided

### ISSUE THREAD

**Issue by sc16me** [dbuezas/icsee-ptz#13]
R80X20-PQL
SW VER: V5.00.R02.0003075b.10010.243114.0000000
HW VER: XM530_R80X20-PQL_8M

The motion sensor does not work on integrations of versions 3.xx The "motion" object is not provided
Works on version 2.0.2

**Comment by dbuezas** [comment]
Do you see any errors in the logs?
Can you remove an re add a camera to make sure it was not a migration issue please?

**Comment by sc16me** [comment]
Уровень: ОШИБКА
Logger: homeassistant
Source: helpers/entity.py:742
First occurred: 13:33:07 (8 occurrences)
Last logged: 13:33:36

Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity None


Уровень: ПРЕДУПРЕЖДЕНИЕ
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:729
First occurred: 13:33:07 (7 occurrences)
Last logged: 13:33:36

Entity None (<class 'custom_components.icsee_ptz.binary_sensor.Alarm'>) does not have a platform, this may be caused by adding it manually instead of with an EntityComponent helper, please report it to the custom integration author.
Entity None (<class 'custom_components.icsee_ptz.switch.AlarmSwitch'>) does not have a platform, this may be caused by adding it manually instead of with an EntityComponent helper, please report it to the custom integration author.
Entity None (<class 'custom_components.icsee_ptz.select.DayNightColorSelect'>) does not have a platform, this may be caused by adding it manually instead of with an EntityComponent helper, please report it to the custom integration author.


Уровень: ОШИБКА
Logger: homeassistant.components.switch
Source: custom_components/icsee_ptz/switch.py:61
Integration: Выключатель (documentation, issues)
First occurred: 13:33:31 (2 occurrences)
Last logged: 13:33:35

Error while setting up icsee_ptz platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/icsee_ptz/switch.py", line 32, in async_setup_entry
    new_entities.append(AlarmSwitch(hass, entry, "MotionDetect", channel))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icsee_ptz/switch.py", line 61, in __init__
    assert self._attr_unique_id  # set by ICSeeEntity
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError


Уровень: ОШИБКА
Logger: homeassistant.components.binary_sensor
Source: custom_components/icsee_ptz/binary_sensor.py:62
Integration: Бинарный сенсор (documentation, issues)
First occurred: 13:33:05 (3 occurrences)
Last logged: 13:33:35

Error while setting up icsee_ptz platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/icsee_ptz/binary_sensor.py", line 49, in async_setup_entry
    [
  File "/config/custom_compУровень: ОШИБКА
Logger: homeassistant.components.select
Source: custom_components/icsee_ptz/select.py:53
Integration: Выбор (documentation, issues)
First occurred: 13:33:31 (2 occurrences)
Last logged: 13:33:35

Error while setting up icsee_ptz platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/icsee_ptz/select.py", line 28, in async_setup_entry
    [
  File "/config/custom_components/icsee_ptz/select.py", line 29, in <listcomp>
    DayNightColorSelect(hass, entry, channel)
  File "/config/custom_components/icsee_ptz/select.py", line 53, in __init__
    assert self._attr_unique_id  # set by ICSeeEntity
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
onents/icsee_ptz/binary_sensor.py", line 50, in <listcomp>
    Alarm(hass, entry, channel)
  File "/config/custom_components/icsee_ptz/binary_sensor.py", line 62, in __init__
    assert self._attr_unique_id  # set by ICSeeEntity
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by sc16me** [comment]
> Can you remove an re add a camera to make sure it was not a migration issue please?

I deleted the integration completely, rebooted HA, then installed the integration, rebooted HA again. As a result, version 3.xx does not work, version 2.0.2 works

**Comment by dbuezas** [comment]
Ok, that's odd. It is working fine for me. I'll take a deeper look soon.

**Comment by uowis** [comment]
This the same issue i have : 
`Error while setting up icsee_ptz platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/icsee_ptz/switch.py", line 32, in async_setup_entry
    new_entities.append(AlarmSwitch(hass, entry, "MotionDetect", channel))
  File "/config/custom_components/icsee_ptz/switch.py", line 61, in __init__
    assert self._attr_unique_id  # set by ICSeeEntity
AssertionError`

**Comment by dbuezas** [comment]
Ok, I think your system is unable to get the mac address of the camera. You are not alone so I'll go back to using the camera's serial number as unique id.

I think this is the same issue reported in #10 so I'll close this one and let's continue there
